astro:
  - paths:
      - "**/*.astro"
      - "src/layouts/**"

blog:
  - paths:
      - "src/content/blog/**"

config:
  - paths:
      - ".github/**"
      - "astro.config.*"
      - "tsconfig.*"
      - "**/package.json"

styles:
  - paths:
      - "src/styles/**"
      - "**/*.css"
      - "**/*.scss"
