name: Validate PR title and commits

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TO_MAIN }}
